In [1]:
#1. Write a Python program to print the NumPy version in your system.
import numpy as np
print(np.version)

<module 'numpy.version' from 'C:\\Users\\SHAKEB\\anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [2]:
#2. Write a Python program to reverse an array (first element becomes last).
import numpy as np
x = np.array([1,2,3,4,5])
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[1 2 3 4 5]
Reverse array:
[5 4 3 2 1]


In [3]:
#3. Write a Python program to convert a list and tuple into arrays.
import numpy as np
y= [1,2,3,4,5]
print(type(y))
ar1=np.array(y)
print("list into array:", ar1)
type(ar1)
z= ([1,2,3], [4,5,6])
type(z)
ar2=np.array(z)
print("tuple into array:", ar2)
print(type(ar2))


<class 'list'>
list into array: [1 2 3 4 5]
tuple into array: [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [4]:
#4. Write a Python program to find common values between two arrays.
a1= np.array([1,2,3,4])
print("a1:", a1)
a2= np.array([4,5,3,7])
print("a2:", a2)
print("Common values between two arrays:")
print(np.intersect1d(a1, a2))

a1: [1 2 3 4]
a2: [4 5 3 7]
Common values between two arrays:
[3 4]


In [5]:
#5. Write a Python program compare two arrays using numpy.
a1= np.array([1,2])
print("a1:", a1)
a2= np.array([4,3])
print("a2:", a2)
print("By comparing two arrays")
print("a1 > a2")
print(np.greater(a1, a2))
print("a1 >= a2")
print(np.greater_equal(a1, a2))
print("a1 < a2")
print(np.less(a1, a2))
print("a1 <= a2")
print(np.less_equal(a1, a2))



a1: [1 2]
a2: [4 3]
By comparing two arrays
a1 > a2
[False False]
a1 >= a2
[False False]
a1 < a2
[ True  True]
a1 <= a2
[ True  True]


In [6]:
#6. Write a Python program to change the dimension of an array.
a1= np.array([1,2,3,4])
print(a1)
print (f'dimension of a1 is:', np.ndim(a1))
a2=np.reshape(a1,(2,2))
print('by changing the dimension:\n', a2)
print(f'the dimension after changing is:', np.ndim(a2))

[1 2 3 4]
dimension of a1 is: 1
by changing the dimension:
 [[1 2]
 [3 4]]
the dimension after changing is: 2


In [7]:
#7. Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.
arr1= np.arange(1,100)
n= arr1[(arr1 % 3 == 0) | (arr1 % 5 == 0)]
print(n[:100])
print(f'sum of all multiple of 3 or 5 below 100 is:', n.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
sum of all multiple of 3 or 5 below 100 is: 2318


In [8]:
#8. Write a Python program to convert a NumPy array into Python list structure. 
arr2= np.array([1,2,3,4])
print(arr2)
print(type(arr2))
l1= arr2.tolist()
print(l1)
print(type(l1))


[1 2 3 4]
<class 'numpy.ndarray'>
[1, 2, 3, 4]
<class 'list'>


In [9]:
#9. Write a Python program to how to add an extra column to a numpy array.
arr1=np.array([1,2,3,4,5,6])
a1=np.reshape(arr1,(2,3))
print('array a1:\n', a1)
arr2=np.array([7,8,9,4])
a2=np.reshape(arr2,(2,2))
print('array a2:\n', a2)
#to add extra column
print('after adding a array a2 as a column:')
print(np.append(a1, a2, axis=1))

array a1:
 [[1 2 3]
 [4 5 6]]
array a2:
 [[7 8]
 [9 4]]
after adding a array a2 as a column:
[[1 2 3 7 8]
 [4 5 6 9 4]]


In [10]:
#10. Write a Python program to check whether the numpy array is empty or not.
x= np.random.randn(2,3)
print(x)
print('the size of array x is:', x.size)
y= np.array([])
print(y)
print('the size of array y is:', y.size)

[[ 0.50516701 -0.79438661 -0.36970887]
 [ 0.7644085   0.88665777 -1.73786695]]
the size of array x is: 6
[]
the size of array y is: 0


In [11]:
#11. Write a Python program to normalize a 3x3 random matrix.
y= np.random.randn(3,3)
print(y)
ymax, ymin = y.max(), y.min()
y = (y - ymin)/(ymax - ymin)
print("After normalization we get:")
print(y)

[[-1.13005798 -0.21001652  0.19525005]
 [-0.71169077  0.70953791  0.85826836]
 [ 0.7985228   2.52157284 -0.02189571]]
After normalization we get:
[[0.         0.25195358 0.36293593]
 [0.11456997 0.50377379 0.54450366]
 [0.52814232 1.         0.30347051]]


In [12]:
#12. How to ignore all numpy warnings (not recommended)?
data = np.random.randn(50).reshape(10, 5) * np.nan
np.seterr(all="ignore")
np.nanmedian(data, axis=1)

C:\Users\SHAKEB\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1119: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [13]:
#13. How to swap two rows of an array?
x = np.array([[1,2,1], [4,7,5], [9,4,3], [1,2,0]])
print(x)
x[[0, 2]] = x[[2, 0]]
print('after swaping the two rows we get:\n', x)

[[1 2 1]
 [4 7 5]
 [9 4 3]
 [1 2 0]]
after swaping the two rows we get:
 [[9 4 3]
 [4 7 5]
 [1 2 1]
 [1 2 0]]


In [14]:
#14. Python program to create a random vector of size 10 and sort it.
y= np.random.randn(10)
print(y)
y.sort()
print("array after sorting:")
print(y)

[ 0.91747123  0.07107281 -0.16508038 -1.65600712 -0.20643631  1.34435145
 -0.74025895  1.87135582  0.09794495 -1.53133366]
array after sorting:
[-1.65600712 -1.53133366 -0.74025895 -0.20643631 -0.16508038  0.07107281
  0.09794495  0.91747123  1.34435145  1.87135582]


In [15]:
#15. Write a Python program to check two random arrays are equal or not.
x = np.random.randn(6)
print("First array:")
print(x)
y = np.random.randn(6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[ 0.44977475 -0.11401274  0.83390466 -1.02374633  0.48361445 -1.35111585]
Second array:
[-0.94381746  1.19920975  1.50665643  0.5529249   0.0794644  -0.33504955]
Test above two arrays are equal or not!
False


In [16]:
#16. Write a Python program to add, subtract, multiply, divide arguments element-wise.
print(np.add(1.0, 4.0))
print(np.subtract(1.0, 4.0))
print(np.multiply(1.0, 4.0))
print(np.divide(1.0, 4.0))

5.0
-3.0
4.0
0.25


In [142]:
#17. Write a Python program to get the dates of yesterday, today and tomorrow.
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("Yestraday date: ",yesterday)
print("Today date: ",today)
print("Tomorrow date: ",tomorrow)

Yestraday date:  2022-06-25
Today date:  2022-06-26
Tomorrow date:  2022-06-27
